#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18449
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ACMDistribuidores")]
	public partial class AccesoDatosDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertCategorias(Categorias instance);
    partial void UpdateCategorias(Categorias instance);
    partial void DeleteCategorias(Categorias instance);
    partial void InsertProveedores(Proveedores instance);
    partial void UpdateProveedores(Proveedores instance);
    partial void DeleteProveedores(Proveedores instance);
    #endregion
		
		public AccesoDatosDataContext() : 
				base(global::CapaDatos.Properties.Settings.Default.ACMDistribuidoresConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public AccesoDatosDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Categorias> Categorias
		{
			get
			{
				return this.GetTable<Categorias>();
			}
		}
		
		public System.Data.Linq.Table<Proveedores> Proveedores
		{
			get
			{
				return this.GetTable<Proveedores>();
			}
		}
		
		public System.Data.Linq.Table<VistaPedido> VistaPedido
		{
			get
			{
				return this.GetTable<VistaPedido>();
			}
		}
		
		public System.Data.Linq.Table<VistaProductos> VistaProductos
		{
			get
			{
				return this.GetTable<VistaProductos>();
			}
		}
		
		public System.Data.Linq.Table<VistaReporteEntrada> VistaReporteEntrada
		{
			get
			{
				return this.GetTable<VistaReporteEntrada>();
			}
		}
		
		public System.Data.Linq.Table<VistaReporteProductos> VistaReporteProductos
		{
			get
			{
				return this.GetTable<VistaReporteProductos>();
			}
		}
		
		public System.Data.Linq.Table<VistaReporteSalida> VistaReporteSalida
		{
			get
			{
				return this.GetTable<VistaReporteSalida>();
			}
		}
		
		public System.Data.Linq.Table<VistaSalidas> VistaSalidas
		{
			get
			{
				return this.GetTable<VistaSalidas>();
			}
		}
		
		public System.Data.Linq.Table<VistaUsuarios> VistaUsuarios
		{
			get
			{
				return this.GetTable<VistaUsuarios>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarExistenciasEntrada")]
		public int spActualizarExistenciasEntrada([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadIngresada", DbType="Int")] System.Nullable<int> cantidadIngresada)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, cantidadIngresada);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarExistenciasPedido")]
		public int spActualizarExistenciasPedido([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadSolicitada", DbType="Int")] System.Nullable<int> cantidadSolicitada)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, cantidadSolicitada);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarImagenProducto")]
		public int spActualizarImagenProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevaImagen", DbType="VarBinary(1)")] System.Data.Linq.Binary nuevaImagen)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, nuevaImagen);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarNombreCategoria")]
		public int spActualizarNombreCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoNombre", DbType="NVarChar(255)")] string nuevoNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevaDescripcion", DbType="NVarChar(256)")] string nuevaDescripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria, nuevoNombre, nuevaDescripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarPrecioProveedor")]
		public int spActualizarPrecioProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoPrecio", DbType="Money")] System.Nullable<decimal> nuevoPrecio)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, nuevoPrecio);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarProducto")]
		public int spActualizarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoNombre", DbType="NVarChar(256)")] string nuevoNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevaDescripcion", DbType="NVarChar(256)")] string nuevaDescripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioProveedor", DbType="Money")] System.Nullable<decimal> precioProveedor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, nuevoNombre, nuevaDescripcion, precioProveedor);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarProveedor")]
		public int spActualizarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProveedor", DbType="Int")] System.Nullable<int> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoNombre", DbType="NVarChar(256)")] string nuevoNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoNit", DbType="NVarChar(256)")] string nuevoNit, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevaDireccion", DbType="NVarChar(256)")] string nuevaDireccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoTelefono", DbType="NVarChar(256)")] string nuevoTelefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevaCelular", DbType="NVarChar(256)")] string nuevaCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoNombreContacto", DbType="NVarChar(256)")] string nuevoNombreContacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoEmail", DbType="NVarChar(256)")] string nuevoEmail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor, nuevoNombre, nuevoNit, nuevaDireccion, nuevoTelefono, nuevaCelular, nuevoNombreContacto, nuevoEmail);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spActualizarUsuario")]
		public int spActualizarUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="UniqueIdentifier")] System.Nullable<System.Guid> idUser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoPrimerNombre", DbType="NVarChar(256)")] string nuevoPrimerNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoSegundoNombre", DbType="NVarChar(256)")] string nuevoSegundoNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoPrimerApellidos", DbType="NVarChar(256)")] string nuevoPrimerApellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoSegundoApellidos", DbType="NVarChar(256)")] string nuevoSegundoApellidos, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevaCedula", DbType="NVarChar(50)")] string nuevaCedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoTelefono", DbType="NVarChar(25)")] string nuevoTelefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoCelular", DbType="NVarChar(25)")] string nuevoCelular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoEmail", DbType="NVarChar(256)")] string nuevoEmail)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUser, nuevoPrimerNombre, nuevoSegundoNombre, nuevoPrimerApellidos, nuevoSegundoApellidos, nuevaCedula, nuevoTelefono, nuevoCelular, nuevoEmail);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarCategoria")]
		public ISingleResult<spConsultarCategoriaResult> spConsultarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Buscar", DbType="NVarChar(256)")] string buscar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), buscar);
			return ((ISingleResult<spConsultarCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarCategorias")]
		public ISingleResult<spConsultarCategoriasResult> spConsultarCategorias()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spConsultarCategoriasResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarIdCategoria")]
		public ISingleResult<spConsultarIdCategoriaResult> spConsultarIdCategoria()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spConsultarIdCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarIdEntrada")]
		public ISingleResult<spConsultarIdEntradaResult> spConsultarIdEntrada()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spConsultarIdEntradaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarIdProveedores")]
		public ISingleResult<spConsultarIdProveedoresResult> spConsultarIdProveedores()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spConsultarIdProveedoresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarIdSalida")]
		public ISingleResult<spConsultarIdSalidaResult> spConsultarIdSalida()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spConsultarIdSalidaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarProducto")]
		public ISingleResult<spConsultarProductoResult> spConsultarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(256)")] string buscar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), buscar);
			return ((ISingleResult<spConsultarProductoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarProductosCategoria")]
		public ISingleResult<VistaProductos> spConsultarProductosCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(256)")] string buscar)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), buscar);
			return ((ISingleResult<VistaProductos>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarProveedor")]
		public ISingleResult<spConsultarProveedorResult> spConsultarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreProveedor", DbType="NVarChar(256)")] string nombreProveedor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreProveedor);
			return ((ISingleResult<spConsultarProveedorResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spConsultarProveedores")]
		public ISingleResult<spConsultarProveedoresResult> spConsultarProveedores()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<spConsultarProveedoresResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearCategoria")]
		public int spCrearCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="NVarChar(255)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(256)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearCategoriaXML")]
		public int spCrearCategoriaXML([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(256)")] string descripcion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria, descripcion);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearDetalleEntrada")]
		public int spCrearDetalleEntrada([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEntrada", DbType="Int")] System.Nullable<int> idEntrada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NuevoPrecioProveedor", DbType="Money")] System.Nullable<decimal> nuevoPrecioProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadIngresada", DbType="Int")] System.Nullable<int> cantidadIngresada)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEntrada, idProducto, nuevoPrecioProveedor, cantidadIngresada);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearDetalleProveedor")]
		public int spCrearDetalleProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProveedor", DbType="Int")] System.Nullable<int> idProveedor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, idProveedor);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearDetalleSalida")]
		public int spCrearDetalleSalida([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSalida", DbType="Int")] System.Nullable<int> idSalida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadIngresada", DbType="Int")] System.Nullable<int> cantidadIngresada)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSalida, idProducto, cantidadIngresada);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearDetalleSalidaXML")]
		public int spCrearDetalleSalidaXML([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSalida", DbType="Int")] System.Nullable<int> idSalida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CantidadIngresada", DbType="Int")] System.Nullable<int> cantidadIngresada)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSalida, idProducto, cantidadIngresada);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearEntrada")]
		public int spCrearEntrada([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaEntrada", DbType="Date")] System.Nullable<System.DateTime> fechaEntrada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="UniqueIdentifier")] System.Nullable<System.Guid> idUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fechaEntrada, idUser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearEntradaXML")]
		public int spCrearEntradaXML([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdEntrada", DbType="Int")] System.Nullable<int> idEntrada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FechaEntrada", DbType="Date")] System.Nullable<System.DateTime> fechaEntrada, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="UniqueIdentifier")] System.Nullable<System.Guid> idUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEntrada, fechaEntrada, idUser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearProducto")]
		public int spCrearProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="NVarChar(256)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreProducto", DbType="NVarChar(256)")] string nombreProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(256)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioProveedor", DbType="Money")] System.Nullable<decimal> precioProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Existencias", DbType="Int")] System.Nullable<int> existencias, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Categoria", DbType="Int")] System.Nullable<int> categoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), codigo, nombreProducto, descripcion, precioProveedor, existencias, categoria);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearProductoXML")]
		public int spCrearProductoXML([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Codigo", DbType="NVarChar(256)")] string codigo, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreProducto", DbType="NVarChar(256)")] string nombreProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Descripcion", DbType="NVarChar(256)")] string descripcion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrecioProveedor", DbType="Money")] System.Nullable<decimal> precioProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Existencias", DbType="Int")] System.Nullable<int> existencias, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Categoria", DbType="Int")] System.Nullable<int> categoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, codigo, nombreProducto, descripcion, precioProveedor, existencias, categoria);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearProveedor")]
		public int spCrearProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreProveedor", DbType="NVarChar(256)")] string nombreProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ciudad", DbType="NVarChar(256)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(256)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NVarChar(256)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="NVarChar(256)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreContacto", DbType="NVarChar(256)")] string nombreContacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(256)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombreProveedor, ciudad, direccion, telefono, celular, nombreContacto, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearProveedorXML")]
		public int spCrearProveedorXML([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProveedor", DbType="Int")] System.Nullable<int> idProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreProveedor", DbType="NVarChar(256)")] string nombreProveedor, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Ciudad", DbType="NVarChar(256)")] string ciudad, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Direccion", DbType="NVarChar(256)")] string direccion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NVarChar(256)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="NVarChar(256)")] string celular, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NombreContacto", DbType="NVarChar(256)")] string nombreContacto, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(256)")] string email)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor, nombreProveedor, ciudad, direccion, telefono, celular, nombreContacto, email);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearSalida")]
		public int spCrearSalida([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="UniqueIdentifier")] System.Nullable<System.Guid> idUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fecha, idUser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearSalidaXML")]
		public int spCrearSalidaXML([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdSalida", DbType="Int")] System.Nullable<int> idSalida, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="UniqueIdentifier")] System.Nullable<System.Guid> idUser)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idSalida, fecha, idUser);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spCrearUsuario")]
		public int spCrearUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdUser", DbType="UniqueIdentifier")] System.Nullable<System.Guid> idUser, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerNombre", DbType="NVarChar(256)")] string primerNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoNombre", DbType="NVarChar(256)")] string segundoNombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrimerApellido", DbType="NVarChar(256)")] string primerApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SegundoApellido", DbType="NVarChar(256)")] string segundoApellido, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="NVarChar(50)")] string cedula, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Telefono", DbType="NVarChar(256)")] string telefono, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Email", DbType="NVarChar(256)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Celular", DbType="NVarChar(256)")] string celular)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idUser, primerNombre, segundoNombre, primerApellido, segundoApellido, cedula, telefono, email, celular);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarCategoria")]
		public int spEliminarCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdCategoria", DbType="Int")] System.Nullable<int> idCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idCategoria);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarDetalleUsuario")]
		public int spEliminarDetalleUsuario([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdDetalleUsuario", DbType="UniqueIdentifier")] System.Nullable<System.Guid> idDetalleUsuario)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idDetalleUsuario);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarProducto")]
		public int spEliminarProducto([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProducto", DbType="Int")] System.Nullable<int> idProducto)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spEliminarProveedor")]
		public int spEliminarProveedor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdProveedor", DbType="Int")] System.Nullable<int> idProveedor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProveedor);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerIdCategoria")]
		public int spObtenerIdCategoria()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerIdDetalleEntrada")]
		public int spObtenerIdDetalleEntrada()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerIdDetalleProveedor")]
		public int spObtenerIdDetalleProveedor()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerIdDetalleSalida")]
		public int spObtenerIdDetalleSalida()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerIdEntrada")]
		public int spObtenerIdEntrada()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerIdProducto")]
		public int spObtenerIdProducto()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerIdProductoCategoria")]
		public ISingleResult<spObtenerIdProductoCategoriaResult> spObtenerIdProductoCategoria([global::System.Data.Linq.Mapping.ParameterAttribute(Name="FK_IdCategoria", DbType="Int")] System.Nullable<int> fK_IdCategoria)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fK_IdCategoria);
			return ((ISingleResult<spObtenerIdProductoCategoriaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerIdProveedor")]
		public int spObtenerIdProveedor()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.spObtenerIdSalida")]
		public int spObtenerIdSalida()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Categorias")]
	public partial class Categorias : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdCategoria;
		
		private string _NombreCategoria;
		
		private string _DescripcionCategoria;
		
		private int _Estado;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdCategoriaChanging(int value);
    partial void OnIdCategoriaChanged();
    partial void OnNombreCategoriaChanging(string value);
    partial void OnNombreCategoriaChanged();
    partial void OnDescripcionCategoriaChanging(string value);
    partial void OnDescripcionCategoriaChanged();
    partial void OnEstadoChanging(int value);
    partial void OnEstadoChanged();
    #endregion
		
		public Categorias()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this.OnIdCategoriaChanging(value);
					this.SendPropertyChanging();
					this._IdCategoria = value;
					this.SendPropertyChanged("IdCategoria");
					this.OnIdCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this.OnNombreCategoriaChanging(value);
					this.SendPropertyChanging();
					this._NombreCategoria = value;
					this.SendPropertyChanged("NombreCategoria");
					this.OnNombreCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionCategoria", DbType="NVarChar(255)")]
		public string DescripcionCategoria
		{
			get
			{
				return this._DescripcionCategoria;
			}
			set
			{
				if ((this._DescripcionCategoria != value))
				{
					this.OnDescripcionCategoriaChanging(value);
					this.SendPropertyChanging();
					this._DescripcionCategoria = value;
					this.SendPropertyChanged("DescripcionCategoria");
					this.OnDescripcionCategoriaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Proveedores")]
	public partial class Proveedores : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdProveedor;
		
		private string _NombreProveedor;
		
		private string _NIT;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _NombreContacto;
		
		private string _EMail;
		
		private int _EstadoProveedor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdProveedorChanging(int value);
    partial void OnIdProveedorChanged();
    partial void OnNombreProveedorChanging(string value);
    partial void OnNombreProveedorChanged();
    partial void OnNITChanging(string value);
    partial void OnNITChanged();
    partial void OnDireccionChanging(string value);
    partial void OnDireccionChanged();
    partial void OnTelefonoChanging(string value);
    partial void OnTelefonoChanged();
    partial void OnCelularChanging(string value);
    partial void OnCelularChanged();
    partial void OnNombreContactoChanging(string value);
    partial void OnNombreContactoChanged();
    partial void OnEMailChanging(string value);
    partial void OnEMailChanged();
    partial void OnEstadoProveedorChanging(int value);
    partial void OnEstadoProveedorChanged();
    #endregion
		
		public Proveedores()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this.OnIdProveedorChanging(value);
					this.SendPropertyChanging();
					this._IdProveedor = value;
					this.SendPropertyChanged("IdProveedor");
					this.OnIdProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProveedor", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProveedor
		{
			get
			{
				return this._NombreProveedor;
			}
			set
			{
				if ((this._NombreProveedor != value))
				{
					this.OnNombreProveedorChanging(value);
					this.SendPropertyChanging();
					this._NombreProveedor = value;
					this.SendPropertyChanged("NombreProveedor");
					this.OnNombreProveedorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="NVarChar(256)")]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this.OnNITChanging(value);
					this.SendPropertyChanging();
					this._NIT = value;
					this.SendPropertyChanged("NIT");
					this.OnNITChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(256)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this.OnDireccionChanging(value);
					this.SendPropertyChanging();
					this._Direccion = value;
					this.SendPropertyChanged("Direccion");
					this.OnDireccionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(256)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this.OnTelefonoChanging(value);
					this.SendPropertyChanging();
					this._Telefono = value;
					this.SendPropertyChanged("Telefono");
					this.OnTelefonoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NVarChar(256)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this.OnCelularChanging(value);
					this.SendPropertyChanging();
					this._Celular = value;
					this.SendPropertyChanged("Celular");
					this.OnCelularChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreContacto", DbType="NVarChar(256)")]
		public string NombreContacto
		{
			get
			{
				return this._NombreContacto;
			}
			set
			{
				if ((this._NombreContacto != value))
				{
					this.OnNombreContactoChanging(value);
					this.SendPropertyChanging();
					this._NombreContacto = value;
					this.SendPropertyChanged("NombreContacto");
					this.OnNombreContactoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(256)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this.OnEMailChanging(value);
					this.SendPropertyChanging();
					this._EMail = value;
					this.SendPropertyChanged("EMail");
					this.OnEMailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoProveedor", DbType="Int NOT NULL")]
		public int EstadoProveedor
		{
			get
			{
				return this._EstadoProveedor;
			}
			set
			{
				if ((this._EstadoProveedor != value))
				{
					this.OnEstadoProveedorChanging(value);
					this.SendPropertyChanging();
					this._EstadoProveedor = value;
					this.SendPropertyChanged("EstadoProveedor");
					this.OnEstadoProveedorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaPedido")]
	public partial class VistaPedido
	{
		
		private int _IdSalida;
		
		private System.DateTime _FechaSalida;
		
		private int _IdProducto;
		
		private string _Codigo;
		
		private string _NombreProducto;
		
		private string _NombreUsuario;
		
		private int _CantidadSalida;
		
		private string _NombreCategoria;
		
		public VistaPedido()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSalida", DbType="Int NOT NULL")]
		public int IdSalida
		{
			get
			{
				return this._IdSalida;
			}
			set
			{
				if ((this._IdSalida != value))
				{
					this._IdSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSalida", DbType="DateTime NOT NULL")]
		public System.DateTime FechaSalida
		{
			get
			{
				return this._FechaSalida;
			}
			set
			{
				if ((this._FechaSalida != value))
				{
					this._FechaSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreUsuario", DbType="NVarChar(510) NOT NULL", CanBeNull=false)]
		public string NombreUsuario
		{
			get
			{
				return this._NombreUsuario;
			}
			set
			{
				if ((this._NombreUsuario != value))
				{
					this._NombreUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadSalida", DbType="Int NOT NULL")]
		public int CantidadSalida
		{
			get
			{
				return this._CantidadSalida;
			}
			set
			{
				if ((this._CantidadSalida != value))
				{
					this._CantidadSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this._NombreCategoria = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaProductos")]
	public partial class VistaProductos
	{
		
		private int _IdProducto;
		
		private string _Codigo;
		
		private string _NombreProducto;
		
		private string _Descripcion;
		
		private decimal _PrecioProveedor;
		
		private System.Nullable<decimal> _PrecioVentaMayorista;
		
		private System.Nullable<decimal> _PrecioVentaMinorista;
		
		private int _Existencias;
		
		private string _NombreCategoria;
		
		private string _NombreProveedor;
		
		public VistaProductos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProveedor", DbType="Money NOT NULL")]
		public decimal PrecioProveedor
		{
			get
			{
				return this._PrecioProveedor;
			}
			set
			{
				if ((this._PrecioProveedor != value))
				{
					this._PrecioProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaMayorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioVentaMayorista
		{
			get
			{
				return this._PrecioVentaMayorista;
			}
			set
			{
				if ((this._PrecioVentaMayorista != value))
				{
					this._PrecioVentaMayorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaMinorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioVentaMinorista
		{
			get
			{
				return this._PrecioVentaMinorista;
			}
			set
			{
				if ((this._PrecioVentaMinorista != value))
				{
					this._PrecioVentaMinorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Existencias", DbType="Int NOT NULL")]
		public int Existencias
		{
			get
			{
				return this._Existencias;
			}
			set
			{
				if ((this._Existencias != value))
				{
					this._Existencias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this._NombreCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProveedor", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProveedor
		{
			get
			{
				return this._NombreProveedor;
			}
			set
			{
				if ((this._NombreProveedor != value))
				{
					this._NombreProveedor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaReporteEntrada")]
	public partial class VistaReporteEntrada
	{
		
		private int _IdEntrada;
		
		private System.DateTime _FechaEntrada;
		
		private int _IdProducto;
		
		private string _Codigo;
		
		private string _NombreProducto;
		
		private string _Descripcion;
		
		private int _CantidadEntrada;
		
		private System.Nullable<decimal> _precioEntrada;
		
		private decimal _Precio_proveedor;
		
		private System.Nullable<decimal> _PrecioMayorista;
		
		private System.Nullable<decimal> _Precio_Minorista;
		
		private int _Existencias;
		
		private int _FK_IdCategoria;
		
		private int _EstadoProducto;
		
		private int _IdCategoria;
		
		private string _Categoria;
		
		private int _IdDetalleProveedor;
		
		private int _Fk_Id_Proveedor;
		
		private int _Fk_Id_Producto;
		
		private int _IdProveedor;
		
		private string _NombreProveedor;
		
		private string _NIT;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _NombreContacto;
		
		private string _EMail;
		
		private int _EstadoProveedor;
		
		public VistaReporteEntrada()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdEntrada", DbType="Int NOT NULL")]
		public int IdEntrada
		{
			get
			{
				return this._IdEntrada;
			}
			set
			{
				if ((this._IdEntrada != value))
				{
					this._IdEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEntrada", DbType="DateTime NOT NULL")]
		public System.DateTime FechaEntrada
		{
			get
			{
				return this._FechaEntrada;
			}
			set
			{
				if ((this._FechaEntrada != value))
				{
					this._FechaEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadEntrada", DbType="Int NOT NULL")]
		public int CantidadEntrada
		{
			get
			{
				return this._CantidadEntrada;
			}
			set
			{
				if ((this._CantidadEntrada != value))
				{
					this._CantidadEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_precioEntrada", DbType="Money")]
		public System.Nullable<decimal> precioEntrada
		{
			get
			{
				return this._precioEntrada;
			}
			set
			{
				if ((this._precioEntrada != value))
				{
					this._precioEntrada = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio_proveedor", DbType="Money NOT NULL")]
		public decimal Precio_proveedor
		{
			get
			{
				return this._Precio_proveedor;
			}
			set
			{
				if ((this._Precio_proveedor != value))
				{
					this._Precio_proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioMayorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioMayorista
		{
			get
			{
				return this._PrecioMayorista;
			}
			set
			{
				if ((this._PrecioMayorista != value))
				{
					this._PrecioMayorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio_Minorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> Precio_Minorista
		{
			get
			{
				return this._Precio_Minorista;
			}
			set
			{
				if ((this._Precio_Minorista != value))
				{
					this._Precio_Minorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Existencias", DbType="Int NOT NULL")]
		public int Existencias
		{
			get
			{
				return this._Existencias;
			}
			set
			{
				if ((this._Existencias != value))
				{
					this._Existencias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_IdCategoria", DbType="Int NOT NULL")]
		public int FK_IdCategoria
		{
			get
			{
				return this._FK_IdCategoria;
			}
			set
			{
				if ((this._FK_IdCategoria != value))
				{
					this._FK_IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoProducto", DbType="Int NOT NULL")]
		public int EstadoProducto
		{
			get
			{
				return this._EstadoProducto;
			}
			set
			{
				if ((this._EstadoProducto != value))
				{
					this._EstadoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetalleProveedor", DbType="Int NOT NULL")]
		public int IdDetalleProveedor
		{
			get
			{
				return this._IdDetalleProveedor;
			}
			set
			{
				if ((this._IdDetalleProveedor != value))
				{
					this._IdDetalleProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Id_Proveedor", DbType="Int NOT NULL")]
		public int Fk_Id_Proveedor
		{
			get
			{
				return this._Fk_Id_Proveedor;
			}
			set
			{
				if ((this._Fk_Id_Proveedor != value))
				{
					this._Fk_Id_Proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Id_Producto", DbType="Int NOT NULL")]
		public int Fk_Id_Producto
		{
			get
			{
				return this._Fk_Id_Producto;
			}
			set
			{
				if ((this._Fk_Id_Producto != value))
				{
					this._Fk_Id_Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Int NOT NULL")]
		public int IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProveedor", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProveedor
		{
			get
			{
				return this._NombreProveedor;
			}
			set
			{
				if ((this._NombreProveedor != value))
				{
					this._NombreProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="NVarChar(256)")]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this._NIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(256)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(256)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NVarChar(256)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreContacto", DbType="NVarChar(256)")]
		public string NombreContacto
		{
			get
			{
				return this._NombreContacto;
			}
			set
			{
				if ((this._NombreContacto != value))
				{
					this._NombreContacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(256)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoProveedor", DbType="Int NOT NULL")]
		public int EstadoProveedor
		{
			get
			{
				return this._EstadoProveedor;
			}
			set
			{
				if ((this._EstadoProveedor != value))
				{
					this._EstadoProveedor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaReporteProductos")]
	public partial class VistaReporteProductos
	{
		
		private int _IdProducto;
		
		private string _Codigo;
		
		private string _NombreProducto;
		
		private string _Descripcion;
		
		private System.Data.Linq.Binary _Imagen;
		
		private System.Nullable<int> _UnidadPorCaja;
		
		private decimal _PrecioProveedor;
		
		private System.Nullable<decimal> _PrecioVentaMayorista;
		
		private System.Nullable<decimal> _PrecioVentaMinorista;
		
		private int _Existencias;
		
		private int _FK_IdCategoria;
		
		private int _EstadoProducto;
		
		private int _IdCategoria;
		
		private string _Categoria;
		
		private int _Estado;
		
		private int _IdDetalleProveedor;
		
		private int _Fk_Id_Proveedor;
		
		private int _Fk_Id_Producto;
		
		private int _IdProveedor;
		
		private string _NombreProveedor;
		
		private string _NIT;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _NombreContacto;
		
		private string _EMail;
		
		private int _EstadoProveedor;
		
		public VistaReporteProductos()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Imagen", DbType="VarBinary(MAX)", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Imagen
		{
			get
			{
				return this._Imagen;
			}
			set
			{
				if ((this._Imagen != value))
				{
					this._Imagen = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UnidadPorCaja", DbType="Int")]
		public System.Nullable<int> UnidadPorCaja
		{
			get
			{
				return this._UnidadPorCaja;
			}
			set
			{
				if ((this._UnidadPorCaja != value))
				{
					this._UnidadPorCaja = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProveedor", DbType="Money NOT NULL")]
		public decimal PrecioProveedor
		{
			get
			{
				return this._PrecioProveedor;
			}
			set
			{
				if ((this._PrecioProveedor != value))
				{
					this._PrecioProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaMayorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioVentaMayorista
		{
			get
			{
				return this._PrecioVentaMayorista;
			}
			set
			{
				if ((this._PrecioVentaMayorista != value))
				{
					this._PrecioVentaMayorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaMinorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioVentaMinorista
		{
			get
			{
				return this._PrecioVentaMinorista;
			}
			set
			{
				if ((this._PrecioVentaMinorista != value))
				{
					this._PrecioVentaMinorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Existencias", DbType="Int NOT NULL")]
		public int Existencias
		{
			get
			{
				return this._Existencias;
			}
			set
			{
				if ((this._Existencias != value))
				{
					this._Existencias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_IdCategoria", DbType="Int NOT NULL")]
		public int FK_IdCategoria
		{
			get
			{
				return this._FK_IdCategoria;
			}
			set
			{
				if ((this._FK_IdCategoria != value))
				{
					this._FK_IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoProducto", DbType="Int NOT NULL")]
		public int EstadoProducto
		{
			get
			{
				return this._EstadoProducto;
			}
			set
			{
				if ((this._EstadoProducto != value))
				{
					this._EstadoProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Categoria", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Categoria
		{
			get
			{
				return this._Categoria;
			}
			set
			{
				if ((this._Categoria != value))
				{
					this._Categoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetalleProveedor", DbType="Int NOT NULL")]
		public int IdDetalleProveedor
		{
			get
			{
				return this._IdDetalleProveedor;
			}
			set
			{
				if ((this._IdDetalleProveedor != value))
				{
					this._IdDetalleProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Id_Proveedor", DbType="Int NOT NULL")]
		public int Fk_Id_Proveedor
		{
			get
			{
				return this._Fk_Id_Proveedor;
			}
			set
			{
				if ((this._Fk_Id_Proveedor != value))
				{
					this._Fk_Id_Proveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_Id_Producto", DbType="Int NOT NULL")]
		public int Fk_Id_Producto
		{
			get
			{
				return this._Fk_Id_Producto;
			}
			set
			{
				if ((this._Fk_Id_Producto != value))
				{
					this._Fk_Id_Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Int NOT NULL")]
		public int IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProveedor", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProveedor
		{
			get
			{
				return this._NombreProveedor;
			}
			set
			{
				if ((this._NombreProveedor != value))
				{
					this._NombreProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="NVarChar(256)")]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this._NIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(256)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(256)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NVarChar(256)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreContacto", DbType="NVarChar(256)")]
		public string NombreContacto
		{
			get
			{
				return this._NombreContacto;
			}
			set
			{
				if ((this._NombreContacto != value))
				{
					this._NombreContacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(256)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoProveedor", DbType="Int NOT NULL")]
		public int EstadoProveedor
		{
			get
			{
				return this._EstadoProveedor;
			}
			set
			{
				if ((this._EstadoProveedor != value))
				{
					this._EstadoProveedor = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaReporteSalida")]
	public partial class VistaReporteSalida
	{
		
		private int _IdSalida;
		
		private System.DateTime _FechaSalida;
		
		private int _IdDetalleSalida;
		
		private int _IdProducto;
		
		private string _Codigo;
		
		private string _NombreProducto;
		
		private string _Descripcion;
		
		private int _CantidadSalida;
		
		private decimal _PrecioProveedor;
		
		private System.Nullable<decimal> _PrecioVentaMayorista;
		
		private System.Nullable<decimal> _PrecioVentaMinorista;
		
		private int _Existencias;
		
		private string _NombreCategoria;
		
		private System.Guid _IdUsuario;
		
		private string _PrimerNombre;
		
		private string _SegundoNombre;
		
		private string _PrimerApellido;
		
		private string _SegundoApellido;
		
		private string _Cedula;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _Email;
		
		public VistaReporteSalida()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSalida", DbType="Int NOT NULL")]
		public int IdSalida
		{
			get
			{
				return this._IdSalida;
			}
			set
			{
				if ((this._IdSalida != value))
				{
					this._IdSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSalida", DbType="DateTime NOT NULL")]
		public System.DateTime FechaSalida
		{
			get
			{
				return this._FechaSalida;
			}
			set
			{
				if ((this._FechaSalida != value))
				{
					this._FechaSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdDetalleSalida", DbType="Int NOT NULL")]
		public int IdDetalleSalida
		{
			get
			{
				return this._IdDetalleSalida;
			}
			set
			{
				if ((this._IdDetalleSalida != value))
				{
					this._IdDetalleSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadSalida", DbType="Int NOT NULL")]
		public int CantidadSalida
		{
			get
			{
				return this._CantidadSalida;
			}
			set
			{
				if ((this._CantidadSalida != value))
				{
					this._CantidadSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProveedor", DbType="Money NOT NULL")]
		public decimal PrecioProveedor
		{
			get
			{
				return this._PrecioProveedor;
			}
			set
			{
				if ((this._PrecioProveedor != value))
				{
					this._PrecioProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaMayorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioVentaMayorista
		{
			get
			{
				return this._PrecioVentaMayorista;
			}
			set
			{
				if ((this._PrecioVentaMayorista != value))
				{
					this._PrecioVentaMayorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaMinorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioVentaMinorista
		{
			get
			{
				return this._PrecioVentaMinorista;
			}
			set
			{
				if ((this._PrecioVentaMinorista != value))
				{
					this._PrecioVentaMinorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Existencias", DbType="Int NOT NULL")]
		public int Existencias
		{
			get
			{
				return this._Existencias;
			}
			set
			{
				if ((this._Existencias != value))
				{
					this._Existencias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this._NombreCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombre", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PrimerNombre
		{
			get
			{
				return this._PrimerNombre;
			}
			set
			{
				if ((this._PrimerNombre != value))
				{
					this._PrimerNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="NVarChar(255)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this._SegundoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerApellido", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PrimerApellido
		{
			get
			{
				return this._PrimerApellido;
			}
			set
			{
				if ((this._PrimerApellido != value))
				{
					this._PrimerApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="NVarChar(255)")]
		public string SegundoApellido
		{
			get
			{
				return this._SegundoApellido;
			}
			set
			{
				if ((this._SegundoApellido != value))
				{
					this._SegundoApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="NVarChar(50)")]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(25)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NVarChar(25)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaSalidas")]
	public partial class VistaSalidas
	{
		
		private int _IdSalida;
		
		private System.DateTime _FechaSalida;
		
		private int _Fk_IdProducto;
		
		private string _NombreProducto;
		
		private int _CantidadSalida;
		
		private System.Nullable<decimal> _PrecioVentaMayorista;
		
		private System.Nullable<decimal> _Precio;
		
		public VistaSalidas()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSalida", DbType="Int NOT NULL")]
		public int IdSalida
		{
			get
			{
				return this._IdSalida;
			}
			set
			{
				if ((this._IdSalida != value))
				{
					this._IdSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaSalida", DbType="DateTime NOT NULL")]
		public System.DateTime FechaSalida
		{
			get
			{
				return this._FechaSalida;
			}
			set
			{
				if ((this._FechaSalida != value))
				{
					this._FechaSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fk_IdProducto", DbType="Int NOT NULL")]
		public int Fk_IdProducto
		{
			get
			{
				return this._Fk_IdProducto;
			}
			set
			{
				if ((this._Fk_IdProducto != value))
				{
					this._Fk_IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CantidadSalida", DbType="Int NOT NULL")]
		public int CantidadSalida
		{
			get
			{
				return this._CantidadSalida;
			}
			set
			{
				if ((this._CantidadSalida != value))
				{
					this._CantidadSalida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaMayorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioVentaMayorista
		{
			get
			{
				return this._PrecioVentaMayorista;
			}
			set
			{
				if ((this._PrecioVentaMayorista != value))
				{
					this._PrecioVentaMayorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(33,5)")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.VistaUsuarios")]
	public partial class VistaUsuarios
	{
		
		private System.Guid _IdUsuario;
		
		private string _PrimerNombre;
		
		private string _SegundoNombre;
		
		private string _PrimerApellido;
		
		private string _SegundoApellido;
		
		private string _Cedula;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _Email;
		
		private System.Nullable<int> _Estado;
		
		public VistaUsuarios()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdUsuario", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid IdUsuario
		{
			get
			{
				return this._IdUsuario;
			}
			set
			{
				if ((this._IdUsuario != value))
				{
					this._IdUsuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerNombre", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PrimerNombre
		{
			get
			{
				return this._PrimerNombre;
			}
			set
			{
				if ((this._PrimerNombre != value))
				{
					this._PrimerNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoNombre", DbType="NVarChar(255)")]
		public string SegundoNombre
		{
			get
			{
				return this._SegundoNombre;
			}
			set
			{
				if ((this._SegundoNombre != value))
				{
					this._SegundoNombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrimerApellido", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string PrimerApellido
		{
			get
			{
				return this._PrimerApellido;
			}
			set
			{
				if ((this._PrimerApellido != value))
				{
					this._PrimerApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="NVarChar(255)")]
		public string SegundoApellido
		{
			get
			{
				return this._SegundoApellido;
			}
			set
			{
				if ((this._SegundoApellido != value))
				{
					this._SegundoApellido = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cedula", DbType="NVarChar(50)")]
		public string Cedula
		{
			get
			{
				return this._Cedula;
			}
			set
			{
				if ((this._Cedula != value))
				{
					this._Cedula = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(25)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NVarChar(25)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(255)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this._Email = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int")]
		public System.Nullable<int> Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class spConsultarCategoriaResult
	{
		
		private int _IdCategoria;
		
		private string _NombreCategoria;
		
		private string _DescripcionCategoria;
		
		private int _Estado;
		
		public spConsultarCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this._NombreCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionCategoria", DbType="NVarChar(255)")]
		public string DescripcionCategoria
		{
			get
			{
				return this._DescripcionCategoria;
			}
			set
			{
				if ((this._DescripcionCategoria != value))
				{
					this._DescripcionCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class spConsultarCategoriasResult
	{
		
		private int _IdCategoria;
		
		private string _NombreCategoria;
		
		private string _DescripcionCategoria;
		
		private int _Estado;
		
		public spConsultarCategoriasResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdCategoria", DbType="Int NOT NULL")]
		public int IdCategoria
		{
			get
			{
				return this._IdCategoria;
			}
			set
			{
				if ((this._IdCategoria != value))
				{
					this._IdCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this._NombreCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DescripcionCategoria", DbType="NVarChar(255)")]
		public string DescripcionCategoria
		{
			get
			{
				return this._DescripcionCategoria;
			}
			set
			{
				if ((this._DescripcionCategoria != value))
				{
					this._DescripcionCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="Int NOT NULL")]
		public int Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this._Estado = value;
				}
			}
		}
	}
	
	public partial class spConsultarIdCategoriaResult
	{
		
		private System.Nullable<int> _Column1;
		
		public spConsultarIdCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class spConsultarIdEntradaResult
	{
		
		private System.Nullable<int> _Column1;
		
		public spConsultarIdEntradaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class spConsultarIdProveedoresResult
	{
		
		private System.Nullable<int> _Column1;
		
		public spConsultarIdProveedoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class spConsultarIdSalidaResult
	{
		
		private System.Nullable<int> _Column1;
		
		public spConsultarIdSalidaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class spConsultarProductoResult
	{
		
		private int _IdProducto;
		
		private string _Codigo;
		
		private string _NombreProducto;
		
		private string _Descripcion;
		
		private decimal _PrecioProveedor;
		
		private System.Nullable<decimal> _PrecioVentaMayorista;
		
		private System.Nullable<decimal> _PrecioVentaMinorista;
		
		private int _Existencias;
		
		private string _NombreCategoria;
		
		private string _NombreProveedor;
		
		public spConsultarProductoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProducto", DbType="Int NOT NULL")]
		public int IdProducto
		{
			get
			{
				return this._IdProducto;
			}
			set
			{
				if ((this._IdProducto != value))
				{
					this._IdProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProducto", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProducto
		{
			get
			{
				return this._NombreProducto;
			}
			set
			{
				if ((this._NombreProducto != value))
				{
					this._NombreProducto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(MAX)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this._Descripcion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioProveedor", DbType="Money NOT NULL")]
		public decimal PrecioProveedor
		{
			get
			{
				return this._PrecioProveedor;
			}
			set
			{
				if ((this._PrecioProveedor != value))
				{
					this._PrecioProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaMayorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioVentaMayorista
		{
			get
			{
				return this._PrecioVentaMayorista;
			}
			set
			{
				if ((this._PrecioVentaMayorista != value))
				{
					this._PrecioVentaMayorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecioVentaMinorista", DbType="Decimal(22,5)")]
		public System.Nullable<decimal> PrecioVentaMinorista
		{
			get
			{
				return this._PrecioVentaMinorista;
			}
			set
			{
				if ((this._PrecioVentaMinorista != value))
				{
					this._PrecioVentaMinorista = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Existencias", DbType="Int NOT NULL")]
		public int Existencias
		{
			get
			{
				return this._Existencias;
			}
			set
			{
				if ((this._Existencias != value))
				{
					this._Existencias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreCategoria", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string NombreCategoria
		{
			get
			{
				return this._NombreCategoria;
			}
			set
			{
				if ((this._NombreCategoria != value))
				{
					this._NombreCategoria = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProveedor", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProveedor
		{
			get
			{
				return this._NombreProveedor;
			}
			set
			{
				if ((this._NombreProveedor != value))
				{
					this._NombreProveedor = value;
				}
			}
		}
	}
	
	public partial class spConsultarProveedorResult
	{
		
		private int _IdProveedor;
		
		private string _NombreProveedor;
		
		private string _NIT;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _NombreContacto;
		
		private string _EMail;
		
		private int _EstadoProveedor;
		
		public spConsultarProveedorResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Int NOT NULL")]
		public int IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProveedor", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProveedor
		{
			get
			{
				return this._NombreProveedor;
			}
			set
			{
				if ((this._NombreProveedor != value))
				{
					this._NombreProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="NVarChar(256)")]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this._NIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(256)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(256)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NVarChar(256)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreContacto", DbType="NVarChar(256)")]
		public string NombreContacto
		{
			get
			{
				return this._NombreContacto;
			}
			set
			{
				if ((this._NombreContacto != value))
				{
					this._NombreContacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(256)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoProveedor", DbType="Int NOT NULL")]
		public int EstadoProveedor
		{
			get
			{
				return this._EstadoProveedor;
			}
			set
			{
				if ((this._EstadoProveedor != value))
				{
					this._EstadoProveedor = value;
				}
			}
		}
	}
	
	public partial class spConsultarProveedoresResult
	{
		
		private int _IdProveedor;
		
		private string _NombreProveedor;
		
		private string _NIT;
		
		private string _Direccion;
		
		private string _Telefono;
		
		private string _Celular;
		
		private string _NombreContacto;
		
		private string _EMail;
		
		private int _EstadoProveedor;
		
		public spConsultarProveedoresResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdProveedor", DbType="Int NOT NULL")]
		public int IdProveedor
		{
			get
			{
				return this._IdProveedor;
			}
			set
			{
				if ((this._IdProveedor != value))
				{
					this._IdProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreProveedor", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
		public string NombreProveedor
		{
			get
			{
				return this._NombreProveedor;
			}
			set
			{
				if ((this._NombreProveedor != value))
				{
					this._NombreProveedor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NIT", DbType="NVarChar(256)")]
		public string NIT
		{
			get
			{
				return this._NIT;
			}
			set
			{
				if ((this._NIT != value))
				{
					this._NIT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Direccion", DbType="NVarChar(256)")]
		public string Direccion
		{
			get
			{
				return this._Direccion;
			}
			set
			{
				if ((this._Direccion != value))
				{
					this._Direccion = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefono", DbType="NVarChar(256)")]
		public string Telefono
		{
			get
			{
				return this._Telefono;
			}
			set
			{
				if ((this._Telefono != value))
				{
					this._Telefono = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Celular", DbType="NVarChar(256)")]
		public string Celular
		{
			get
			{
				return this._Celular;
			}
			set
			{
				if ((this._Celular != value))
				{
					this._Celular = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreContacto", DbType="NVarChar(256)")]
		public string NombreContacto
		{
			get
			{
				return this._NombreContacto;
			}
			set
			{
				if ((this._NombreContacto != value))
				{
					this._NombreContacto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMail", DbType="NVarChar(256)")]
		public string EMail
		{
			get
			{
				return this._EMail;
			}
			set
			{
				if ((this._EMail != value))
				{
					this._EMail = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EstadoProveedor", DbType="Int NOT NULL")]
		public int EstadoProveedor
		{
			get
			{
				return this._EstadoProveedor;
			}
			set
			{
				if ((this._EstadoProveedor != value))
				{
					this._EstadoProveedor = value;
				}
			}
		}
	}
	
	public partial class spObtenerIdProductoCategoriaResult
	{
		
		private System.Nullable<int> _Column1;
		
		public spObtenerIdProductoCategoriaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
